name: contenthook
version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: ContentHook.API/Dockerfile
    container_name: contenthook_api
    restart: unless-stopped
    ports:
      - "5050:8080"
      - "5051:8081"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - ASPNETCORE_Kestrel__Limits__MaxRequestBodySize=524288000
      - OpenAI__ApiKey=${OPENAI_API_KEY}
      - OpenAI__Model=${OPENAI_MODEL}
    networks:
      - contenthook-network
  db:
    image: postgres:16-alpine
    container_name: contenthook_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    volumes:
      - local_pgdata:/data/postgres
    networks:
      - contenthook-network
  pgadmin:
    image: dpage/pgadmin4
    container_name: contenthook_pgadmin
    restart: always
    ports:
      - "5055:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - contenthook-network
  webui:
    build:
      context: ./contenthook.webui
      dockerfile: Dockerfile
    container_name: contenthook_webui
    restart: unless-stopped
    ports:
      - "3000:5173"
    depends_on:
      - api
    stdin_open: true
    tty: true
    networks:
      - contenthook-network
volumes:
  local_pgdata:
  pgadmin-data:
networks:
  contenthook-network:
    driver: bridge